### PR TITLE
Revert "Awesome Books with ES6"

### PR DESCRIPTION
**Pull request by Masuduzzaman811**
Reverts Masuduzzaman811/Awesome_Books_ES6#1

## Awesome Books with ES6
I rebuilt our previous Awesome Books apps with ES6 features and JS modules. I have used two modules in this project, one for the awesome boos class and another for the local time.

## Key Requirements:
- Use ES6 syntax.
- Divide code into modules. Save each module in a separate file in the modules dir.
- Keep all functionalities of the app without errors.
- Refactor the methods and functions to arrow functions.
- Use let and const in the correct way.
- Use luxon library to show current date and time.

### CODE REVIEW

**Comment by Masuduzzaman811** [comment]
I accidentally merged my pull request. In my previous pull request, I got a change request to change the Add-Book section and contact section display to none by default. 
Before the change:
image

After the change:
image

I've made the changes as required.

**Comment by Masuduzzaman811** [comment]
This project has no linter errors. Please check my first pull request.
[previous pull request](https://github.com/Masuduzzaman811/Awesome_Books_ES6/pull/1)

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @Masuduzzaman811,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by omar-muhamad** [comment]
> I accidentally merged my pull request. In my previous pull request, I got a change request to change the Add-Book section and contact section display to none by default. Before the change: image
> 
> After the change: image
> 
> I've made the changes as required.

Hi @Masuduzzaman811,
Next time, if you did the same mistake please push to the same branch and make a new PR from the same branch to the main

**Pull request merged**
